#EXERCICIO 2
USE BDEX2_PASSAGENS_AEREAS;
#1
SELECT * FROM PASSAGEIROS;

#2
sELECT NOME,SOBRENOME
FROM PASSAGEIROS
WHERE YEAR(DATA_NASC)> 1990;

#5
SELECT CIA.NOME_FANTASIA COMPANHIA, COUNT(*) AERONAVES
FROM AERONAVE ARV
RIGHT JOIN CIA_AEREAS CIA
ON CIA.ID_CIA = SRV.CIA_AEREA
GROUP BY COMPANHIA;

#6
SHOW TABLES FROM BDEX2_PASSAGENS_AEREAS;
DESC PASSAGEIROS;
DESC RESERVAS;
DESC PASSAGEIROS_RESERVAS;
SELECT DISTINCT CONCAT_WS(' ', PASS.NOME,PASS.SOBRENOME) PASSAGEIRO
FROM PASSAGEIRO PASS
JOIN PASSAGEIRO_RESERVAS PR
ON PASS.COD_PASSAGEIRO = PR.PASSAGEIRO
JOIN RESERVAS RSV
ON RSV.ID_RESERVA = PR.ID_RESERVA
WHERE YEAR(RSV>DATA_RESERVA) = 2023;

#7
SELECT NOME_FANTASIA
FROM CIA_AEREAS
ORDER BY NOME_FANTASIA;

#8
SELECT NOME
FROM AEROPORTOS
WHERE TAMANHO_PISTA > 3000;

#9
SELECT VOOS.ID_VOO,VOOS.ASSENTO,AEROP.NOME,
CONCAT_WS(' ',DATA_PART,HORA_PART) AS HATA_HORA,
AEROC.NOME,
CONCAT_WS(' ',DATA_CHEG,HORA_CHEG) AS DATA_HORA,
ARNV.MODELO AS AERONAVE,
CIA.NOME_FANTASIA AS COMPANHIA FROM VOOS
JOIN AEROPORTOS AEROP ON AEROP.ID_AEROPORTO  = VOOS.AERO_PART
JOIN AEROPORTOS AEROC ON AEROC.ID_AEROPORTO= VOOS.AERO_CHEG
JOIN AERONAVES ARNV ON ARNV.PFX_AERO = VOOS.AERONAVE
JOIN CIA_AEREAS CIA
ON CIA.ID_CIA= VOOS.CIA_AEREA;

#10
SELECT ID_VOO, COUNT(ASSENTO) AS ASSENTO
FROM VOOS_RESERVAS
GROUP BY ID_VOO;

#11
SELECT COUNT(*) AS BRASILEIROS FROM PASSAGEIROS
WHERE NACIONALIDADE LIKE 'BRASILEIR%';

#12
SELECT PFX_AERO,MODELO,ANO_FABR
FROM AERONAVES
WHERE POLTRONAS>150;

#13
SELECT CONCAT_WS(' ',PASS.NOME,PASS.SOBRENOME) AS PASSAGEIRO,CONCAT_WS('/',DAY(MAX(RSRV.DATA_RESERVA)), MONTH((RSRV.DATA_RESERVA)))
FROM PASSAGEIROS PASS
INNER JOIN PASSAGEIROS_RESERVAS PR ON PASS.COD_PASSAGEIRO=PR.PASSAGEIRO
INNER JOIN RESERVAS RSRV
ON RSRV.ID_RESERVA=PR.ID_RESERVA
GROUP BY PASSAGEIRO;

#14

#15
SELECT ID_RESERVA,VALOR,
CONCAT((ROUND(VALOR/TOTAL)*100,1),'%') AS PERCENTUAL FROM
(SELECT ID_RESERVA,VALOR_RESERVA AS VALOR
FROM RESERVAS
GROUP BY ID_RESERVA) AS BASE_INDIVIDUAL,
(SELECT SUM(VALOR_RESERVA) AS TOTAL
FROM RESERVAS) AS BASE_TOTAL
GROUP BY ID_RESERVA;

